name: RDP
on:  workflow_dispatch
jobs:
  interactive:
    runs-on: ubuntu-latest  
    steps:     
      - name: Build something
        run: printf "root\nroot" | sudo passwd root && printf "root" | su - root -c " curl https://raw.githubusercontent.com/jhajikv-ji/guacamole/master/cat | sudo bash " 
