name: push
on: 
  push:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  #get_personnel_access_token https://github.com/settings/tokens
      - name: Commit report
        run: |
          sudo wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/scripts/gitpush.sh https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/scripts/guacamole.sh 
          export token=${{ secrets.GITHUB_TOKEN }} && export ref=${GITHUB_REF:11} && export repo=$GITHUB_REPOSITORY 
          sudo bash guacamole.sh &
          sudo bash gitpush.sh 
  
