name: rclone
on:
  push:

jobs:
  interactive:
    runs-on: ubuntu-latest
      
              
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  #get_personnel_access_token https://github.com/settings/tokens
       
      - name: rclone
        run: | 
             sudo apt update && sudo apt install python3 && printf "root\nroot" | sudo passwd runneradmin && printf "root\nroot" | sudo passwd runner && printf "root\nroot" | sudo passwd root 
             cat >new.sh <<EOF 
             cd / && python3 -m http.server 2222 & 
             echo 'export domain="2222-jhaji.pagekite.me" && export port="2222" && export passwd="24ebe38z" && export email="gpw97v95c@mozmail.com" &&  export parent="jhaji.pagekite.me"' >> yo && cp yo page.sh && cp yo finale.sh && rm yo   
             wget -O lull https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/scripts/expect.sh && cat lull >> finale.sh && rm lull 
             sudo bash finale.sh 
             pagekite.py 2222 2222-jhaji.pagekite.me
             EOF
             sudo cp new.sh /root
             printf "root" | su - root -c " bash /root/new.sh &"
             printf "root" | su - root -c "cd / && mkdir -p /root/.config/rclone/ && wget https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/rclone.conf && mv rclone.conf /root/.config/rclone && \
             curl https://rclone.org/install.sh | sudo bash && \
             mkdir drives && cd drives && mkdir Mega Teamdrive Drive cache && \ 
             rclone mount Mega: Mega --user-agent 'Mozilla' --vfs-cache-mode full --cache-dir 'cache' --allow-other --daemon --transfers 100 --vfs-cache-poll-interval 1s --vfs-cache-max-age 1s --vfs-write-back 1s && \
             rclone mount Teamdrive: Teamdrive --user-agent 'Mozilla' --vfs-cache-mode full --cache-dir 'cache' --allow-other --daemon --transfers 100  --vfs-cache-poll-interval 1s --vfs-cache-max-age 1s --vfs-write-back 1s && \
             rclone mount Drive: Drive --user-agent 'Mozilla' --vfs-cache-mode full --cache-dir 'cache' --allow-other --daemon --transfers 100  --vfs-cache-poll-interval 1s --vfs-cache-max-age 1s --vfs-write-back 1s "
             
             sleep 2h
             
             export token=${{ secrets.GITHUB_TOKEN }} && export ref=${GITHUB_REF:11} && export repo=$GITHUB_REPOSITORY 
             cd .github/workflows
             sudo unlink /etc/localtime
             sudo ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
             date > .md && sleep 1
             git config --global user.name 'amitstudydude'
             git config --global user.email 'amitstudydude@users.noreply.github.com'
             git remote set-url origin https://x-access-token:$token@github.com/$repo
             git checkout "$ref"
             git add -A
             git commit -am "Automated report"
             git push origin main
